site_name: Thoát nghiện
site_description: Đây là một cuốn sổ tay sẽ giúp bạn thoát nghiện, mãi mãi.
site_author: Allen Carr & Jack Trimpey (Hoàn thiện bởi duykhanh471)  
repo_url: https://github.com/duyk471/thoat-nghien
repo_name: Open a pull request

nav:
  - Home: 'index.md'
  - 'Easyway':
    - 'Thoát nghiện mạng xã hội':
      - 'Bản tuyên ngôn độc lập khỏi mạng xã hội': 'easyway/mxh/index.md'
      - 'Những tình huống khó xử': 'easyway/mxh/tinh-huong-kho-xu.md'
      - 'Lời tạm biệt, và chào đón': 'easyway/mxh/sau-do.md'
    - 'Thoát nghiện video game':
      - 'Hướng dẫn tân thủ': 'easyway/video-game/index.md'
  - 'AVRT':
    - 'Mở đầu': 'avrt/index.md'
    - 'Lời kêu gọi': 'avrt/loi-keu-goi.md'
    - 'Tóm tắt': 'avrt/tom-tat.md'
    - 'Khóa học':
      - 'Bài 1': 'avrt/khoa-hoc/1.md'
      - 'Bài 2': 'avrt/khoa-hoc/2.md'
      - 'Bài 3': 'avrt/khoa-hoc/3.md'
theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - open-in-new-tab